export const AGENTMETHOD = 'AGENTMETHOD';
export const FREEAGENT = 'FREEAGENT';
export const NAPAGENT = 'NAPAGENT';
export const ADDAGENTFX = 'ADDAGENTFX';
export const RMAGENTFX = 'RMAGENTFX';
export const SETAGENTAMP = 'SETAGENTAMP';

export const SETTEMPO = 'SETTEMPO';
export const FUTURECALLBACK = 'FUTURECALLBACK';

export const PLAYPERCUSSIVE = 'PLAYPERCUSSIVE';
export const PLAYMELODIC = 'PLAYMELODIC';
export const PLAYCONCRETE = 'PLAYCONCRETE';

export const QUERY = 'QUERY';
