export const MARKTEXT = 'MARKTEXT';
export const UNMARKTEXT = 'UNMARKTEXT';
export const REPLACETEXT = 'REPLACETEXT';
export const REPLACELINE = 'REPLACELINE';
export const DISPLAYINFO = 'DISPLAYINFO';
export const DISPLAYAGENTSTATE = 'DISPLAYAGENTSTATE';
